src/main/java/pl/lodz/p/it/spjava/dm/web/ListProduktPageBean.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pl.lodz.p.it.spjava.dm.web;

import javax.inject.Named;
import javax.enterprise.context.RequestScoped;
import javax.faces.model.DataModel;
import javax.inject.Inject;
import pl.lodz.p.it.spjava.dm.model.Produkt;
import pl.lodz.p.it.spjava.dm.produkt.ProduktSession;

/**
 *
 * @author java
 */
@Named(value = "listProduktPageBean")
@RequestScoped
public class ListProduktPageBean {
    
    @Inject
    private ProduktSession produktSession;
    
    private DataModel<Produkt> dataModelProdukt;
    private DataModel<Produkt> dataModelOneProdukt;
    
    private String produktSkrot;
    private static String wybranyProdukt;

    public String getWybranyProdukt() {
        return wybranyProdukt;
    }

    public void setWybranyProdukt(String wybranyProdukt) {
        this.wybranyProdukt = wybranyProdukt;
    }
    
    public ListProduktPageBean() {
    }
    
    public DataModel<Produkt> getProduktList() {
        return produktSession.getProduktList();
    }
    
    public String getProduktSkrot() {
        return produktSkrot;
    }
    
    public DataModel<Produkt> getOneProduktList(){
        return produktSession.getOneProduktList(wybranyProdukt);
    }
    
    public String szczegolyProduktu(){
        return "produktDetailsPage";
    }

}

src/main/webapp/template/MainTemplate.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:h="http://java.sun.com/jsf/html">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <meta http-equiv="Cache-Control" content="no-cache,no-store,must-revalidate" />
        <meta http-equiv="Pragma" content="no-cache" />
        <title>Dom Maklerski</title>
        <link href="../resources/cssLayout.css" rel="stylesheet" type="text/css" />
    </head>
    <body>
        <div id="top_1" class="top_1">
            <ui:insert name="TEST_MENU"></ui:insert>
        </div>
        <div id="top_2" class="top_2">
            <div class="horizontal">
                <div><ui:insert name="dropdownProdukty"></ui:insert></div>
                <div><ui:insert name="dropdownRejestracja"></ui:insert></div>
                <div><ui:insert name="przyciskiRejestracja"></ui:insert></div>
                <div><ui:insert name="utworzProduktButton"></ui:insert></div>
                <div><ui:insert name="edytujProduktButton"></ui:insert></div>
            </div>
        </div>
        <div id="content" class="content">
            <ui:insert name="contentLogin"></ui:insert>
            <ui:insert name="contentUtworzKlienta"></ui:insert>
            <ui:insert name="contentUtworzBrokera"></ui:insert>
            <ui:insert name="contentProduktDetails"></ui:insert>
            <ui:insert name="contentOneProduktDetails"></ui:insert>
            <ui:insert name="contentUtworzProdukt"></ui:insert>
            <ui:insert name="contentEdytujProdukt"></ui:insert>
        </div>
        <div id="bottom" class="bottom">
            <center><h:graphicImage value="/resources/Duke_8-copy.png" alt="SoccerDuke" style="width:80px;height:60px;"></h:graphicImage></center>
        </div>
    </body>
</html>

src/main/webapp/template/RegisterTemplate.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:h="http://java.sun.com/jsf/html">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <meta http-equiv="Cache-Control" content="no-cache,no-store,must-revalidate" />
        <meta http-equiv="Pragma" content="no-cache" />
        <title>Dom Maklerski</title>
        <link href="../resources/cssLayout.css" rel="stylesheet" type="text/css" />
        <link href="../resources/cssRegister.css" rel="stylesheet" type="text/css" />
    </head>
    <body>
        <div id="top_1" class="top_1">
            <ui:insert name="TEST_MENU"></ui:insert>
        </div>
        <div id="content" class="reg_cont">
            <ui:insert name="contentUtworzKlienta"></ui:insert>
            <ui:insert name="contentUtworzBrokera"></ui:insert>
        </div>
        <div id="bottom" class="bottom">
            <center><h:graphicImage value="/resources/Duke_8-copy.png" alt="SoccerDuke" style="width:80px;height:60px;"></h:graphicImage></center>
        </div>
    </body>
</html>

src/main/webapp/template/contentLogin.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns="http://www.w3.org/1999/xhtml"
                xmlns:h="http://xmlns.jcp.org/jsf/html">

    <h:panelGrid columns="2">
        <form method="post" action="j_security_check">
            <p class="czcionka">
                ${msg['konto.login']}:
                <input type="text" name= "j_username" />
            </p>
            <p class="czcionka">
                ${msg['konto.haslo']}:
                <input type="password" name= "j_password" />
            </p>
            <p>
                <input class="czcionka" type="submit" value="${msg['przycisk.login']}" />
            </p>
        </form>
    </h:panelGrid>


</ui:composition>

src/main/webapp/template/contentOneProduktDetails.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns:ui="http://java.sun.com/jsf/facelets" 
                xmlns="http://www.w3.org/1999/xhtml"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:c="http://xmlns.jcp.org/jsf/core">
                    
    <h:form id="listaProduktow">
                <h:dataTable style="float: left" value="#{listProduktPageBean.oneProduktList}" var="produkt">
                    <h:column>
                        <c:facet name="header">Kurs</c:facet>
                        #{produkt.kurs}
                    </h:column>
                    <h:column>
                        <c:facet name="header">Nazwa pełna</c:facet>
                        #{produkt.nazwapelna}                       
                    </h:column>
                    <h:column>
                        <c:facet name="header">Skrót</c:facet>
                        #{produkt.skrot}                        
                    </h:column>
                    <h:column>
                        <c:facet name="header">Wielkość emisji</c:facet>
                        #{produkt.stan}                        
                    </h:column>
                </h:dataTable>
    </h:form>
</ui:composition>

src/main/webapp/template/contentProduktDetails.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns:ui="http://java.sun.com/jsf/facelets" 
                xmlns="http://www.w3.org/1999/xhtml"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:c="http://xmlns.jcp.org/jsf/core">
                    
    <h:form id="listaProduktow">
                <h:dataTable style="float: left" value="#{listProduktPageBean.produktList}" var="produkt">
                    <h:column>
                        <c:facet name="header">Kurs</c:facet>
                        #{produkt.kurs}
                    </h:column>
                    <h:column>
                        <c:facet name="header">Nazwa pełna</c:facet>
                        #{produkt.nazwapelna}                       
                    </h:column>
                    <h:column>
                        <c:facet name="header">Skrót</c:facet>
                        #{produkt.skrot}                        
                    </h:column>
                    <h:column>
                        <c:facet name="header">Stan</c:facet>
                        #{produkt.stan}                        
                    </h:column>
                </h:dataTable>
    </h:form>
</ui:composition>

src/main/webapp/template/contentUtworzBrokera.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns:ui="http://java.sun.com/jsf/facelets" 
                xmlns="http://www.w3.org/1999/xhtml"
                xmlns:h="http://java.sun.com/jsf/html">
                    
<h:form>
    <h:panelGrid columns="3">
        
<h:outputLabel value="#{msg['konto.telefon']}" for="phone" />
<h:inputText id="phone" value="#{utworzBrokeraPageBean.nowyBroker.telefonsupport}" title="#{msg['konto.telefon']}" required="true" />
<h:messages for="phone" />

<h:outputLabel value="#{msg['konto.login']}" for="login" />
<h:inputText id="login" value="#{utworzBrokeraPageBean.nowyBroker.login}" title="#{msg['konto.login']}" required="true" />
<h:messages for="login" /> 

<h:outputLabel value="#{msg['konto.haslo']}" for="password" />
<h:inputSecret id="password" value="#{utworzBrokeraPageBean.nowyBroker.haslo}" title="#{msg['konto.haslo']}" required="true" />
<h:messages for="password" />

<h:outputLabel value="#{msg['konto.powtorzHaslo']}" for="passwordRepeat" />
<h:inputSecret id="passwordRepeat" value="#{utworzBrokeraPageBean.hasloPowtorz}" title="#{msg['konto.powtorzHaslo']}" required="true" />
<h:messages for="passwordRepeat" />

<h:outputLabel value="#{msg['konto.imie']}" for="name" />
<h:inputText id="name" value="#{utworzBrokeraPageBean.nowyBroker.imie}" title="#{msg['konto.imie']}" required="true" />
<h:messages for="name" />                                 

<h:outputLabel value="#{msg['konto.nazwisko']}" for="surname" />
<h:inputText id="surname" value="#{utworzBrokeraPageBean.nowyBroker.nazwisko}" title="#{msg['konto.nazwisko']}" required="true" />
<h:messages for="surname" />

<h:outputLabel value="#{msg['konto.email']}" for="email" />
<h:inputText id="email" value="#{utworzBrokeraPageBean.nowyBroker.email}" title="#{msg['konto.email']}" required="true" />
<h:messages for="email" />
                


    </h:panelGrid>
    <p>
        <h:commandButton action="#{utworzBrokeraPageBean.utworz()}" value="#{msg['zarejestruj']}" />
        <h:commandButton action="homePage" value="#{msg['anuluj']}" immediate="true" />
    </p>
</h:form>
</ui:composition>

src/main/webapp/template/contentUtworzKlienta.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns:ui="http://java.sun.com/jsf/facelets" 
                xmlns="http://www.w3.org/1999/xhtml"
                xmlns:h="http://java.sun.com/jsf/html">
                    
<h:form>
    <h:panelGrid columns="3">
                                 
<h:outputLabel value="#{msg['konto.login']}" for="login" />
<h:inputText id="login" value="#{pageBean.konto.login}" title="#{msg['konto.login']}" required="true" />
<h:messages for="login" />                

<h:outputLabel value="#{msg['konto.haslo']}" for="password" />
<h:inputSecret id="password" value="#{otworzRachunek.rachunek.haslo}" title="#{msg['konto.haslo']}" required="true" />
<h:messages for="password" />

<h:outputLabel value="#{msg['konto.powtorzHaslo']}" for="passwordRepeat" />
<h:inputSecret id="passwordRepeat" value="#{otworzRachunek.hasloPowtorz}" title="#{msg['konto.powtorzHaslo']}" required="true" />
<h:messages for="passwordRepeat" />
                    
<h:outputLabel value="#{msg['konto.imie']}" for="name" />
<h:inputText id="name" value="#{otworzRachunek.rachunek.imie}" title="#{msg['konto.imie']}" required="true" />
<h:messages for="name" />


<h:outputLabel value="#{msg['konto.nazwisko']}" for="surname" />
<h:inputText id="surname" value="#{otworzRachunek.rachunek.nazwisko}" title="#{msg['konto.nazwisko']}" required="true" />
<h:messages for="surname" />

<h:outputLabel value="#{msg['konto.email']}" for="email" />
<h:inputText id="email" value="#{otworzRachunek.rachunek.email}" title="#{msg['konto.email']}" required="true" />
<h:messages for="email" />
                

<h:outputLabel value="#{msg['konto.telefon']}" for="phone" />
<h:inputText id="phone" value="#{otworzRachunek.rachunek.telefon}" title="#{msg['konto.telefon']}" required="false" />
<h:messages for="phone" />

<h:outputLabel value="#{msg['konto.nip']}" for="nip" />
<h:inputText id="nip" value="#{pageBean.konto.nip}" title="#{msg['konto.nip']}" required="true" />
<h:messages for="nip" />

    </h:panelGrid>
    <p>
        <h:commandButton action="#{pageBean.potwierdzRejestracje}" value="#{msg['zarejestruj']}" />
        <h:commandButton action="homePage" value="#{msg['anuluj']}" immediate="true" />
    </p>
</h:form>
</ui:composition>

src/main/webapp/template/przyciskiRejestracja.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns:ui="http://java.sun.com/jsf/facelets" 
                xmlns="http://www.w3.org/1999/xhtml"
                xmlns:h="http://java.sun.com/jsf/html">
                    
<h:form id="rejestrujFormButtons">
    <p>
    <h:commandButton action="#{pageBean.potwierdzRejestracje}" value="#{msg['zarejestruj']}" />
    <h:commandButton action="homePage" value="#{msg['anuluj']}" immediate="true" />
    </p>
</h:form>
</ui:composition>